// <auto-generated />
using DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(MobileDBContext))]
    [Migration("20200904203322_create_database")]
    partial class create_database
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DAL.Entities.Mobile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("Memory");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70);

                    b.Property<string>("OS")
                        .IsRequired()
                        .HasMaxLength(70);

                    b.Property<double>("Price");

                    b.Property<string>("Processor")
                        .IsRequired()
                        .HasMaxLength(70);

                    b.Property<double>("ScreenSize");

                    b.Property<double>("Size");

                    b.Property<string>("VideoThumb");

                    b.Property<double>("Weight");

                    b.HasKey("Id");

                    b.ToTable("Mobiles");
                });

            modelBuilder.Entity("DAL.Entities.MobilePictures", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MobileId");

                    b.Property<string>("Thumb");

                    b.HasKey("Id");

                    b.HasIndex("MobileId");

                    b.ToTable("MobilePictures");
                });

            modelBuilder.Entity("DAL.Entities.MobilePictures", b =>
                {
                    b.HasOne("DAL.Entities.Mobile", "Mobile")
                        .WithMany("MobilePictures")
                        .HasForeignKey("MobileId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
